---
id: schoo-readable-code-2014-12
base_name: chapter-3
tags:
- rabbit
- readable-code
- schoo
presentation_date: 2014-12-9
version: 2014.12.9.0
licenses:
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: 
  speaker_deck_user: 
